language: go

services:
  - docker

before_install:
  - docker build -t mechanic-build .

script:
  - docker run --rm --name mechanic-build -v $PWD/:/build mechanic-build /bin/bash -c "cd build && make" 

