language: c
compiler:
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y sqlite3 libsqlite3-dev

script:
  - make clean generate compile integration-tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
