os: linux
dist: trusty
group: stable

language: python
python:
  - "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y sqlite3 libsqlite3-dev

script:
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)
