sudo: required

language: go

services:
  - docker

before_install:
  - docker build -t mechanic-build .

script:
  - docker run --rm mechanic-build mechanic-build -v $PWD/:/build bash -c "cd build && make" 

